import { create } from 'zustand'
import { persist } from 'zustand/middleware'

export const useThemeStore = create(
  persist(
    (set) => ({
      theme: 'system',
      setTheme: (theme) => set({ theme }),
    }),
    {
      name: 'quicknotes-theme',
    }
  )
)

export const useUIStore = create(
  persist(
    (set) => ({
      sidebarOpen: true,
      desktopSidebarOpen: true,
      notesListWidth: 320,
      notesListOpen: true,
      inspectorOpen: false,
      mobileInspectorOpen: false,
      inspectorWidth: 300,
      quickNoteOpen: false,
      settingsOpen: false,
      shareModalOpen: false,
      shareNoteId: null,
      sharedNotesViewOpen: false,
      exportModalOpen: false,
      importModalOpen: false,
      reminderModalOpen: false,
      reminderNoteId: null,
      reminderTarget: null,
      showTrash: false,
      findReplaceOpen: false,
      noteLinkPopoverOpen: false,
      noteLinkPosition: { x: 0, y: 0 },
      imageUploadOpen: false,
      versionHistoryOpen: false,
      versionHistoryNoteId: null,
      duplicateModalOpen: false,
      currentSort: 'updated-desc',
      showFavorites: false,
      globalSearchOpen: false,
      globalSearchQuery: '',
      focusModeOpen: false,
      linkModalOpen: false,
      archiveViewOpen: false,
      voiceInputActive: false,
      multiSelectMode: false,
      selectedNoteIds: [],
      shortcutsModalOpen: false,
      noteTypesModalOpen: false,
      tasksViewOpen: false,
      todayAgendaOpen: false,
      todayViewToken: 0,
      smartViewModalOpen: false,
      smartViewEditingId: null,
      templateSaveOpen: false,
      helpModalOpen: false,
      privacyModalOpen: false,
      termsModalOpen: false,
      tagManagerOpen: false,
      mobileEditorOpen: false,
      mobileView: 'notes',
      viewMode: 'list',
      translateModalOpen: false,
      translateText: '',
      language: 'en',
      autoSync: true,
      syncInterval: 5,
      syncOnStartup: true,
      showSyncNotifications: true,
      editorSettingsOpen: false,
      htmlEditorOpen: false,
      confirmBeforeDelete: true,
      spellCheck: true,
      showNoteStatistics: true,
      trashRetentionDays: 30,
      notePreviewLines: 2,
      dateFormat: 'relative',
      compactMode: false,
      autoSaveDelay: 300,

  toggleSidebar: () => set((state) => ({ sidebarOpen: !state.sidebarOpen })),
  setSidebarOpen: (open) => set({ sidebarOpen: open }),
  setDesktopSidebarOpen: (open) => set({ desktopSidebarOpen: open }),
  setNotesListWidth: (width) => set({ notesListWidth: width }),
  setNotesListOpen: (open) => set({ notesListOpen: open }),
  toggleNotesList: () => set((state) => ({ notesListOpen: !state.notesListOpen })),
  setInspectorOpen: (open) => set({ inspectorOpen: open }),
  toggleInspector: () => set((state) => ({ inspectorOpen: !state.inspectorOpen })),
  setMobileInspectorOpen: (open) => set({ mobileInspectorOpen: open }),
  setInspectorWidth: (width) => set({ inspectorWidth: width }),
  setQuickNoteOpen: (open) => set({ quickNoteOpen: open }),
  setSettingsOpen: (open) => set({ settingsOpen: open }),
  setShareModalOpen: (open, noteId = null) => set({ shareModalOpen: open, shareNoteId: noteId }),
  setSharedNotesViewOpen: (open) => set({ sharedNotesViewOpen: open }),
  setExportModalOpen: (open) => set({ exportModalOpen: open }),
  setImportModalOpen: (open) => set({ importModalOpen: open }),
  setReminderModalOpen: (open, noteId = null, target = null) => set({
    reminderModalOpen: open,
    reminderNoteId: open ? noteId : null,
    reminderTarget: open ? target : null,
  }),
  setShowTrash: (show) => set({ showTrash: show }),
  setFindReplaceOpen: (open) => set({ findReplaceOpen: open }),
  setNoteLinkPopoverOpen: (open, position = null) => set({
    noteLinkPopoverOpen: open,
    noteLinkPosition: position || { x: 0, y: 0 }
  }),
  setImageUploadOpen: (open) => set({ imageUploadOpen: open }),
  setVersionHistoryOpen: (open, noteId = null) => set({
    versionHistoryOpen: open,
    versionHistoryNoteId: noteId
  }),
  setDuplicateModalOpen: (open) => set({ duplicateModalOpen: open }),
  setCurrentSort: (sort) => set({ currentSort: sort }),
  setShowFavorites: (show) => set({ showFavorites: show, showTrash: false }),
  setGlobalSearchOpen: (open) => set({ globalSearchOpen: open }),
  setGlobalSearchQuery: (query) => set({ globalSearchQuery: query }),
  setFocusModeOpen: (open) => set({ focusModeOpen: open }),
  setLinkModalOpen: (open) => set({ linkModalOpen: open }),
  setArchiveViewOpen: (open) => set({ archiveViewOpen: open }),
  setVoiceInputActive: (active) => set({ voiceInputActive: active }),
  setMultiSelectMode: (mode) => set({ multiSelectMode: mode, selectedNoteIds: [] }),
  setShortcutsModalOpen: (open) => set({ shortcutsModalOpen: open }),
  setNoteTypesModalOpen: (open) => set({ noteTypesModalOpen: open }),
  setTasksViewOpen: (open) => set({ tasksViewOpen: open }),
  setTodayAgendaOpen: (open) => set({ todayAgendaOpen: open }),
  openTodayAgenda: () => set((state) => ({ todayViewToken: state.todayViewToken + 1 })),
  setSmartViewModalOpen: (open, editingId = null) => set({
    smartViewModalOpen: open,
    smartViewEditingId: open ? editingId : null,
  }),
  setTemplateSaveOpen: (open) => set({ templateSaveOpen: open }),
  setHelpModalOpen: (open) => set({ helpModalOpen: open }),
  setPrivacyModalOpen: (open) => set({ privacyModalOpen: open }),
  setMobileEditorOpen: (open) => set({ mobileEditorOpen: open, mobileView: open ? 'editor' : 'notes' }),
  setMobileView: (view) => set({ mobileView: view, mobileEditorOpen: view === 'editor' }),
  setViewMode: (mode) => set({ viewMode: mode }),
  setTermsModalOpen: (open) => set({ termsModalOpen: open }),
  setTagManagerOpen: (open) => set({ tagManagerOpen: open }),
  setTranslateModalOpen: (open) => set({ translateModalOpen: open }),
  setTranslateText: (text) => set({ translateText: text }),
  openTranslateModal: (text) => set({ translateModalOpen: true, translateText: text }),
  setEditorSettingsOpen: (open) => set({ editorSettingsOpen: open }),
  setHTMLEditorOpen: (open) => set({ htmlEditorOpen: open }),
  toggleNoteSelection: (noteId) => set((state) => {
    const isSelected = state.selectedNoteIds.includes(noteId)
    return {
      selectedNoteIds: isSelected
        ? state.selectedNoteIds.filter((id) => id !== noteId)
        : [...state.selectedNoteIds, noteId],
    }
  }),
  clearNoteSelection: () => set({ selectedNoteIds: [], multiSelectMode: false }),
  setLanguage: (lang) => set({ language: lang }),
  setAutoSync: (enabled) => set({ autoSync: enabled }),
  setSyncInterval: (minutes) => set({ syncInterval: minutes }),
  setSyncOnStartup: (enabled) => set({ syncOnStartup: enabled }),
  setShowSyncNotifications: (enabled) => set({ showSyncNotifications: enabled }),
  setConfirmBeforeDelete: (enabled) => set({ confirmBeforeDelete: enabled }),
  setSpellCheck: (enabled) => set({ spellCheck: enabled }),
  setShowNoteStatistics: (enabled) => set({ showNoteStatistics: enabled }),
  setTrashRetentionDays: (days) => set({ trashRetentionDays: days }),
  setNotePreviewLines: (lines) => set({ notePreviewLines: lines }),
  setDateFormat: (format) => set({ dateFormat: format }),
  setCompactMode: (enabled) => set({ compactMode: enabled }),
  setAutoSaveDelay: (delay) => set({ autoSaveDelay: delay }),
}),
    {
      name: 'quicknotes-ui-settings',
      partialize: (state) => ({
        language: state.language,
        currentSort: state.currentSort,
        desktopSidebarOpen: state.desktopSidebarOpen,
        notesListWidth: state.notesListWidth,
        notesListOpen: state.notesListOpen,
        inspectorOpen: state.inspectorOpen,
        inspectorWidth: state.inspectorWidth,
        viewMode: state.viewMode,
        autoSync: state.autoSync,
        syncInterval: state.syncInterval,
        syncOnStartup: state.syncOnStartup,
        showSyncNotifications: state.showSyncNotifications,
        confirmBeforeDelete: state.confirmBeforeDelete,
        spellCheck: state.spellCheck,
        showNoteStatistics: state.showNoteStatistics,
        trashRetentionDays: state.trashRetentionDays,
        notePreviewLines: state.notePreviewLines,
        dateFormat: state.dateFormat,
        compactMode: state.compactMode,
        autoSaveDelay: state.autoSaveDelay,
      }),
    }
  )
)
