-- Baseline schema for a fresh QuickNotes Supabase project.
-- Later migrations tighten these initial constraints, policies, and indexes.

create table public.folders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null
    constraint folders_user_id_fkey references auth.users (id) on delete cascade,
  name text not null,
  icon text not null default 'Folder',
  color text not null default '#10b981',
  parent_id uuid
    constraint folders_parent_id_fkey references public.folders (id) on delete set null,
  sync_status text not null default 'synced',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.notes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null
    constraint notes_user_id_fkey references auth.users (id) on delete cascade,
  folder_id uuid
    constraint notes_folder_id_fkey references public.folders (id) on delete set null,
  title text not null default '',
  content text not null default '',
  tags text[] not null default '{}'::text[],
  starred boolean not null default false,
  pinned boolean not null default false,
  deleted boolean not null default false,
  deleted_at timestamptz,
  archived boolean not null default false,
  archived_at timestamptz,
  reminder timestamptz,
  sort_order integer,
  note_type text default 'standard',
  note_data jsonb,
  sync_status text not null default 'synced',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.tags (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null
    constraint tags_user_id_fkey references auth.users (id) on delete cascade,
  name text not null,
  color text not null default '#3b82f6',
  sync_status text not null default 'synced',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tags_user_id_name_key unique (user_id, name)
);

create table public.note_versions (
  id bigint generated by default as identity primary key,
  note_id uuid not null
    constraint note_versions_note_id_fkey references public.notes (id) on delete cascade,
  title text not null default '',
  content text not null default '',
  note_type text,
  note_data jsonb,
  created_at timestamptz not null default now()
);

create table public.shared_notes (
  id uuid primary key default gen_random_uuid(),
  note_id uuid not null
    constraint shared_notes_note_id_fkey references public.notes (id) on delete cascade,
  shared_by uuid not null
    constraint shared_notes_shared_by_fkey references auth.users (id) on delete cascade,
  shared_with uuid
    constraint shared_notes_shared_with_fkey references auth.users (id) on delete cascade,
  email text,
  permission text not null default 'view',
  status text not null default 'pending',
  share_link text default replace(gen_random_uuid()::text, '-', ''),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint email_or_user check (email is not null or shared_with is not null),
  constraint shared_notes_permission_valid check (permission in ('view', 'edit')),
  constraint shared_notes_status_valid check (status in ('pending', 'accepted', 'declined')),
  constraint shared_notes_share_link_key unique (share_link)
);

create table public.accepted_shares (
  id uuid primary key default gen_random_uuid(),
  note_id uuid not null
    constraint accepted_shares_note_id_fkey references public.notes (id) on delete cascade,
  user_id uuid not null
    constraint accepted_shares_user_id_fkey references auth.users (id) on delete cascade,
  permission text not null default 'view',
  created_at timestamptz not null default now(),
  constraint accepted_shares_note_user_key unique (note_id, user_id),
  constraint accepted_shares_permission_valid check (permission in ('view', 'edit'))
);

create index idx_notes_user_id on public.notes (user_id);
create index idx_notes_folder_id on public.notes (folder_id);
create index idx_notes_updated_at on public.notes (user_id, updated_at desc);
create index idx_folders_user_id on public.folders (user_id);
create index idx_folders_parent_id on public.folders (parent_id);
create index idx_tags_user_id on public.tags (user_id);
create index idx_note_versions_note_id on public.note_versions (note_id);
create index idx_shared_notes_note_id on public.shared_notes (note_id);
create index idx_shared_notes_shared_by on public.shared_notes (shared_by);
create index idx_shared_notes_shared_with on public.shared_notes (shared_with);
create index idx_shared_notes_email on public.shared_notes (email);
create index idx_accepted_shares_note_id on public.accepted_shares (note_id);
create index idx_accepted_shares_user_id on public.accepted_shares (user_id);

create or replace function public.update_updated_at_column()
returns trigger
language plpgsql
set search_path = ''
as $function$
begin
  new.updated_at = now();
  return new;
end;
$function$;

create trigger set_folders_updated_at
before update on public.folders
for each row execute function public.update_updated_at_column();

create trigger set_notes_updated_at
before update on public.notes
for each row execute function public.update_updated_at_column();

create trigger set_tags_updated_at
before update on public.tags
for each row execute function public.update_updated_at_column();

create trigger set_shared_notes_updated_at
before update on public.shared_notes
for each row execute function public.update_updated_at_column();

alter table public.notes enable row level security;
alter table public.folders enable row level security;
alter table public.tags enable row level security;
alter table public.note_versions enable row level security;
alter table public.shared_notes enable row level security;
alter table public.accepted_shares enable row level security;

revoke all on public.notes,
  public.folders,
  public.tags,
  public.note_versions,
  public.shared_notes,
  public.accepted_shares
from anon, authenticated;

revoke all on function public.update_updated_at_column()
from public, anon, authenticated;

grant all on public.notes,
  public.folders,
  public.tags,
  public.note_versions,
  public.shared_notes,
  public.accepted_shares
to service_role;

grant usage, select on all sequences in schema public to service_role;

-- Realtime note updates drive collaborative editor refreshes. Supabase creates
-- the publication before project migrations run; plain PostgreSQL installs may
-- omit it without preventing the schema from being created.
do $block$
begin
  if exists (
    select 1 from pg_publication where pubname = 'supabase_realtime'
  ) and not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'notes'
  ) then
    alter publication supabase_realtime add table public.notes;
  end if;
end;
$block$;
